"""Add Document table

Revision ID: 04943737df64
Revises: 
Create Date: 2025-01-31 15:13:43.835056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04943737df64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='파일 이름 (한국어 Full Text Search 지원)'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='파일 저장 경로'),
    sa.Column('status', postgresql.ENUM('INIT', 'CHUNKING', 'EMBEDDING', 'INDEXING', name='document_status'), nullable=False, comment='파일 처리 상태'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일'),
    sa.Column('modified_at', sa.DateTime(), nullable=False, comment='수정일'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_name', 'documents', [sa.text("to_tsvector('simple', name)")], unique=False, postgresql_using='GIN')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_name', table_name='documents', postgresql_using='GIN')
    op.drop_table('documents')
    # ### end Alembic commands ###
