version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=plog
    ports:
      - "5432:5432"
    networks:
      - plog-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - plog-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

networks:
  plog-network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
